[package]
name = "envn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap={version="4", features=["derive"]}
bunt="0.2"
inquire={version ="0.6"}
bcrypt="0.15"
indicatif="0.17"
rust-crypto="0.2"
aes="0.8"
rand="0.8"
